### ISSUE TITLE
Overtheme improving

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#40] opened 2015-11-16 15:22 UTC
When the awesome overtheme feature is used with the "copy from theme: True" option, MaTiSSe doesn't modifies the only part of the theme that the user specifies into the overtheme section, but changes all the characteristics of the object. For example, if I write

```
---
overtheme:
  - copy-from-theme: True
  - slide:
    - transition: 'diagonal'
    - content:
      - font-size: 130%
---
```

the slide attributes aren't copied from the main theme, but the slide style is reset to a "blank" style.

A very cool feature of the overtheme option could be that all the main theme characteristics are copied, except that specified in the overtheme section.

**Comment by szaghi** [comment] 2015-11-16 16:47
This was already the intended behavior. 

Simply, there was a bug: the slide elements dimension were not recomputed after the overtheme copies data from main theme. In version 1.3.3 is now fixed.

**Closed by szaghi** 2015-11-16 16:47 UTC
